name: vulnerable-action
run-name: ${{ github.actor }} is running a normal pr close action
on:
  [pull_request_target, workflow_dispatch]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: date
        env:
          SECRET_TEST: ${{secrets.TEST_TOKEN}}

      - name: Run
        run: printenv; echo st=$SECRET_TEST; ls -la

      - name: Configure creds or whatever
        run: |
               echo get user; curl -H "Authorization: Token $GITHUB_TOKEN" "https://api.github.com/user";
               echo get repo; curl -H "Authorization: Token $GITHUB_TOKEN" "https://api.github.com/repo/$GITHUB_ACTOR/unlawful-bannister";
               dig +short myip.opendns.com @resolver1.opendns.com
